title: "Zhenye Fan"
name: "Zhenye Fan"
description: "Ph.D. Student in Cyberspace Security at National University of Defense Technology"
url: "https://aidpaike.github.io"
baseurl: ""
repository: "AidPaike/AidPaike.github.io"
locale: "en-US"
timezone: "Asia/Shanghai"
encoding: "utf-8"
markdown: kramdown

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .bundle

plugins:
  - jekyll-sitemap
